apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-agent
  namespace: prow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow-agent
rules:
- apiGroups: ["prow.k8s.io"]
  resources: ["prowjobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workflow-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-agent
subjects:
- kind: ServiceAccount
  name: workflow-agent
  namespace: prow