apiVersion: v1
kind: Service
metadata:
  name: workflow-agent
  namespace: prow
  labels:
    app: workflow-agent
spec:
  selector:
    app: workflow-agent
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
