# SuperNova Role - required for Route53 domain management via Nova
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: supernova-role
  namespace: ack-system
spec:
  name: Nova-DO-NOT-DELETE
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "nova.aws.internal"
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }
  policies:
  - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
  - arn:aws:iam::aws:policy/SecurityAudit
