apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: agent-workflow-config
  namespace: prow
  behavior: create
  # Alias the file to be compatible with each of the deployments
  files:
  - workflows.yaml=agent-workflows.yaml