kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
      SystemdCgroup = false
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: KubeletConfiguration
      cgroupDriver: cgroupfs
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: KubeletConfiguration
      cgroupDriver: cgroupfs
