{
 "title": "ACK Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "NOTE: Metric with only single datapoint show up as zero. (Prometheus Initialization Bug)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Controller Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Reconcile Count",
   "type": "graph",
   "description": "Controller reconciliation total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (increase(controller_runtime_reconcile_total[150s])/150*120)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Errors",
   "type": "graph",
   "description": "Errors during controller reconciliation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(controller_runtime_reconcile_errors_total[150s])/150*120",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Time (p90)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(controller_runtime_reconcile_time_seconds_bucket[150s]))*1000",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Time (p100)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0, rate(controller_runtime_reconcile_time_seconds_bucket[150s]))*1000",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Work Queue Retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "increase(workqueue_retries_total{job=\"ack-controller\"}[150s])/150*120",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ACK Resource Count",
   "type": "timeseries",
   "description": "Count of ACK resources",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "etcd_object_counts{resource=~\".*\\\\.services\\\\.k8s\\\\.aws\"} / on(instance) group_left topk(1, group by (instance) (etcd_object_counts)) > 0",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "AWS API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "AWS API Request Count",
   "type": "graph",
   "description": "Request count for different AWS APIs invoked by ACK service controller",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(ack_outbound_api_requests_total[150s])/150*120",
     "legendFormat": "{{op_id}}"
    }
   ]
  },
  {
   "title": "AWS 4xx Errors",
   "type": "graph",
   "description": "4xx Error count when invoking AWS API from ACK service controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(ack_outbound_api_requests_error_total{status_code=~'4..'}[150s])/150*120",
     "legendFormat": "[{{op_id}} - {{status_code}}]"
    }
   ]
  },
  {
   "title": "AWS 5xx Errors",
   "type": "graph",
   "description": "5xx Error count when invoking AWS API from ACK service controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Net Count" }
   ],
   "targets": [
    {
     "expr": "increase(ack_outbound_api_requests_error_total{status_code=~'5..'}[150s])/150*120",
     "legendFormat": "[{{op_id}} - {{status_code}}]"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Heap Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"ack-controller\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"ack-controller\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "File Descriptors Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percent", "label": "usage" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"ack-controller\"}/process_max_fds{job=\"ack-controller\"}*100",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_count{job=\"ack-controller\"}[150s])/150*120",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\", job=\"ack-controller\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\", job=\"ack-controller\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"1\", job=\"ack-controller\"}",
     "legendFormat": "p100"
    }
   ]
  }
 ]
}