apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  labels:
    grafana_dashboard: "1"

configMapGenerator:
- name: ack-soak-dashboards
  behavior: create
  files:
  - ack-dashboard-source.json