# EKS Addons managed by ACK
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Addon
metadata:
  name: secrets-store-csi
  namespace: ack-system
spec:
  clusterName: ${CLUSTER_NAME}
  name: aws-secrets-store-csi-driver-provider
  configurationValues: |-
    {
      "secrets-store-csi-driver": {
        "syncSecret": {
          "enabled": true
        }
      }
    }
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Addon
metadata:
  name: external-dns-addon
  namespace: ack-system
spec:
  clusterName: ${CLUSTER_NAME}
  name: external-dns
  podIdentityAssociations:
  - roleARN: arn:aws:iam::${ACCOUNT_ID}:role/external-dns-role
    serviceAccount: external-dns
