apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster.yaml
- access-entries.yaml
- addons.yaml
- ecr-pull-through-cache.yaml
- prow-logs-bucket.yaml
- prow-iam-roles.yaml
