# Generated by gen-terraform-env on 2026-05-20T01:50:31Z

region = "us-west-2"
account_id = "822779886699"
flux_version = "2.18.3"
test_infra_org = "ack-prow-staging"
test_infra_repo = "ack-test-infra"
test_infra_branch = "flux-v2-api-upgrade"
stage = "dev"
prow_domain = "gustidia.people.aws.dev"
