apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prow-config
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: prow
  values:
    github:
      organisation: "aws-controllers-k8s"
      bot:
        username: "ack-bot"
        emailID: "82905295"
        personalAccessToken:
          secretName: "prowjob-github-pat-token"
    region: "us-west-2"
    ingress:
      create: true
      annotations:
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/scheme: "internet-facing"
        alb.ingress.kubernetes.io/success-codes: "200-302"
        alb.ingress.kubernetes.io/target-type: "ip"
        alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-FS-1-2-Res-2020-10"
        kubernetes.io/ingress.class: "alb"
    prow:
      domain: "prow.ack.aws.dev"
      presubmitsBucketName: "ack-prow-logs"
      tideStatusReconcilerBucketName: "ack-prow-logs"
    crier:
      serviceAccount:
        name: "prow-deployment-service-account"
    deck:
      serviceAccount:
        name: "prow-deployment-service-account"
    hook:
      scrapeMetrics: true
      serviceAccount:
        name: "prow-deployment-service-account"
    horologium:
      serviceAccount:
        name: "prow-deployment-service-account"
    prowControllerManager:
      scrapeMetrics: true
      serviceAccount:
        name: "prow-deployment-service-account"
    sinker:
      serviceAccount:
        name: "prow-deployment-service-account"
    statusreconciler:
      serviceAccount:
        name: "prow-deployment-service-account"
    tide:
      scrapeMetrics: true
      serviceAccount:
        name: "prow-deployment-service-account"
  chart:
    spec:
      chart: ./prow/config
      sourceRef:
        kind: GitRepository
        name: test-infra