apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prow-data-plane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aws-controllers-k8s/test-infra.git
    targetRevision: HEAD
    path: prow/data-plane
    helm:
      parameters:
      - name: "crier.serviceAccount.name"
        value: "prow-deployment-service-account"
      - name: "deck.serviceAccount.name"
        value: "prow-deployment-service-account"
      - name: "ghproxy.serviceAccount.name"
        value: "prow-deployment-service-account"
      - name: "hook.serviceAccount.name"
        value: "prow-deployment-service-account"
      - name: "horologium.serviceAccount.name"
        value: "prow-deployment-service-account"
      - name: "prowControllerManager.serviceAccount.name"
        value: "prow-deployment-service-account"
      - name: "sinker.serviceAccount.name"
        value: "prow-deployment-service-account"
      - name: "statusreconciler.serviceAccount.name"
        value: "prow-deployment-service-account"
      - name: "tide.serviceAccount.name"
        value: "prow-deployment-service-account"
  destination:
    server: https://kubernetes.default.svc
    namespace: test-pods
  syncPolicy:
    automated:
      prune: true
      selfHeal: true