apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flux-self.yaml
- self-managed-prereqs.yaml
- self-managed-capability.yaml
- self-managed.yaml
- self-managed-pod-identities.yaml
- prow-secrets.yaml
- prow.yaml