apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prow-config
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: prow
  values:
    region: "us-west-2"
    prow:
      domain: "ack.aws.dev"
      presubmitsBucketName: "ack-prow-logs"
      tideStatusReconcilerBucketName: "ack-prow-logs"
    crier:
      serviceAccount:
        name: "prow-deployment-service-account"
    deck:
      service:
        type: "LoadBalancer"
      serviceAccount:
        name: "prow-deployment-service-account"
    hook:
      serviceAccount:
        name: "prow-deployment-service-account"
    horologium:
      serviceAccount:
        name: "prow-deployment-service-account"
    prowControllerManager:
      serviceAccount:
        name: "prow-deployment-service-account"
    sinker:
      serviceAccount:
        name: "prow-deployment-service-account"
    statusreconciler:
      serviceAccount:
        name: "prow-deployment-service-account"
    tide:
      serviceAccount:
        name: "prow-deployment-service-account"
  chart:
    spec:
      chart: ./prow/config
      sourceRef:
        kind: GitRepository
        name: test-infra