# Prow secrets (SecretProviderClass + RBAC) - depends on the Secrets Store CSI
# addon being installed by ACK via self-managed-cluster.
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: test-infra
  path: ./flux/secrets
  prune: true
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: self-managed-vars
  dependsOn:
  - name: ack-addons
  - name: ack-pod-identities
