apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ssm-agent
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: test-infra
  path: ./prow/ssm-agent
  prune: true
  targetNamespace: default
  validation: client