import yaml
from jinja2 import Environment, FileSystemLoader
from datetime import datetime

"""Script to auto-generate labels.yaml file declaring labels to generate
"""

# Load the config to be used with jinja templates.
config = yaml.safe_load(open('./jobs_config.yaml'))
env = Environment(loader=FileSystemLoader('./jinja/config'), trim_blocks=True, lstrip_blocks=True)

def generate_label_sync_config(dst_path):
    config_content = "# Autogenerated. Do NOT update Manually.\n"
    config_content += f'# Last generated on {datetime.now()}.\n#\n'

    template_content = env.get_template("label_sync.jinja2")
    config_content += template_content.render(config)

    with open(dst_path, 'w') as config_file:
        config_file.write(config_content)

if __name__ == "__main__":
    generate_label_sync_config("labels.yaml")