// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package main

import (
	"fmt"
	"html/template"
	"os"
	"slices"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Structure for prow job versions stored in 
// images_config.yaml
type ImageContext struct {
	ImageRepo string            `yaml:"image_repo"`
	Images    map[string]string `yaml:"images"`
}

// Structure for prow job configurations stored in
// jobs.yaml
type Config struct {
	AWSServices                   []string `yaml:"aws_services"`
	CarmTestServices              []string `yaml:"carm_test_services"`
	SoakTestOnReleaseServiceNames []string `yaml:"soak_test_on_release_service_names"`
	CodegenPresubmitServices      []string `yaml:"code_gen_presubmit_services"`
	RuntimePresubmitServices      []string `yaml:"runtime_presubmit_services"`
	ACKTestPresubmitServices      []string `yaml:"acktest_presubmit_services"`
}

func loadImages(imageConfigPath string) (*ImageContext, error) {

	fileData, err := os.ReadFile(imageConfigPath)
	if err != nil {
		return nil, fmt.Errorf("unable to read file %s: %v", imageConfigPath, err)
	}

	var imageContext *ImageContext
	if err = yaml.Unmarshal(fileData, &imageContext); err != nil {
		return nil, fmt.Errorf("unable to unmarshall imageConfig: %v", err)
	}
	return imageContext, nil
}

func loadConfig(configPath string) (*Config, error) {
	fileData, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("unable to read file %s: %v", configPath, err)
	}

	var config *Config
	if err = yaml.Unmarshal(fileData, &config); err != nil {
		return nil, fmt.Errorf("unable to unmarshall imageConfig: %v", err)
	}
	return config, nil
}

func contains(arr []string, s string) bool {
	return slices.Contains(arr, s)
}

func loadTemplates(prowJobType, templateDir string, imageContext *ImageContext, config *Config) (string, error) {

	templateFiles, err := os.ReadDir(templateDir)
	if err != nil {
		return "", fmt.Errorf("unable to read directory %s: %v", templateDir, err)
	}

	var content strings.Builder

	content.WriteString(fmt.Sprintf("%s:\n", prowJobType))
	data := map[string]interface{}{
		"Config":       config,
		"ImageContext": imageContext,
	}

	for _, file := range templateFiles {
		// templateContent, err := template.ParseFS(filename, imageContext.Images[0])
		fileData, _ := os.ReadFile(fmt.Sprintf("%s/%s", templateDir, file.Name()))
		tmpl, err := template.New(file.Name()).Funcs(template.FuncMap{"contains": contains}).Parse(string(fileData))

		if err != nil {
			panic(err)
		}
		err = tmpl.Execute(&content, data)
		if err != nil {
			panic(err)
		}
		content.WriteString("\n")
	}
	return content.String(), err
}

func generateJobs(destinationPath string, imageContext *ImageContext, config *Config) error {
	jinjaPath := "./templates"
	periodicJobsPath := fmt.Sprintf("%s/periodics", jinjaPath)
	postsubmitJobsPath := fmt.Sprintf("%s/postsubmits", jinjaPath)
	presubmitJobsPath := fmt.Sprintf("%s/presubmits", jinjaPath)

	var prowjobsContent strings.Builder
	prowjobsContent.WriteString("# Autogenerated. Do NOT update Manually.\n")
	prowjobsContent.WriteString(fmt.Sprintf("# Last generated on %v\n", time.DateTime))

	periodicsContent, err := loadTemplates("periodics", periodicJobsPath, imageContext, config)
	if err != nil {
		panic(err)
	}
	postSubmitContent, err := loadTemplates("postsubmits", postsubmitJobsPath, imageContext, config)
	if err != nil {
		panic(err)
	}
	presubmitContent, err := loadTemplates("presubmits", presubmitJobsPath, imageContext, config)
	if err != nil {
		panic(err)
	}

	prowjobsContent.WriteString(fmt.Sprintf("%s%s%s", periodicsContent, postSubmitContent, presubmitContent))

	file, err := os.Create(destinationPath)
	if err != nil {
		panic(err)
	}
	_, err = file.WriteString(prowjobsContent.String())
	return err
}

func generateLabelSyncConfig(destinationPath string, config *Config) error {
	jinjaPath := "./templates"

	var configContent strings.Builder
	configContent.WriteString("# Autogenerated. Do NOT update Manually\n")
	configContent.WriteString(fmt.Sprintf("# Last generated on %s.\n#\n", time.DateTime))
	
	tmpl, err := template.ParseFiles(fmt.Sprintf("%s/config/label_sync.tpl", jinjaPath))
	if err != nil {
		return err
	}
	err = tmpl.Execute(&configContent, config)
	if err != nil {
		return err
	}
	file, err := os.Create(destinationPath)
	if err != nil {
		panic(err)
	}
	_, err = file.WriteString(configContent.String())
	return err
}

func main() {
	config, err := loadConfig("./jobs_config.yaml"); 
	if err != nil {
		panic(err)
	}

	imageContext, err := loadImages("./images_config.yaml"); 
	if err != nil {
		panic(err)
	}

	if err := generateJobs("./jobs.yaml", imageContext, config); err != nil {
		panic(err)
	}

	if err := generateLabelSyncConfig("./labels.yaml", config); err != nil {
		panic(err)
	}
}
