apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- job-config-job.yaml

configMapGenerator:
- name: test-config
  namespace: test-pods
  behavior: create
  files:
  - test_config.yaml
- name: label-config
  namespace: test-pods
  behavior: create
  files:
  - labels.yaml
- name: jobs-config
  namespace: test-pods
  behavior: create
  files:
  - jobs_config.yaml