cluster:
  create: true
  # TODO(michaelhtm): Update k8s_version to 1.34.3 once the underlying
  # infra issues are resolved
  k8s_version: 1.28.0

aws:
  region: us-west-2
  token_file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token

debug:
  enabled: true
  dump_controller_logs: true
