#!/usr/bin/env bash
#
# Bootstraps a Terraform environment file from AWS SSM Parameter Store.
#
# On first run: prompts for variables, stores them in SSM, writes .tfvars.
# On subsequent runs: pulls from SSM and writes .tfvars (no prompts).
#
# Usage:
#   ./scripts/bootstrap-env.sh [--force]
#
# Options:
#   --force   Re-prompt for all values even if SSM parameter exists
#
# Storage:
#   SSM Parameter: /ack/test-infra/bootstrap/env
#   Type: SecureString (encrypted at rest)
#
# Output:
#   bootstrap/environment/<stage>.tfvars
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOTSTRAP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_DIR="${BOOTSTRAP_DIR}/environment"

SSM_PREFIX="/ack/test-infra/bootstrap/env"
SSM_PARAM="${SSM_PREFIX}"
FORCE=false
STAGE=""

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# --- Helpers ---
prompt() {
  local description="$1"
  local default="$2"
  local value
  read -rp "  ${description} [${default}]: " value
  echo "${value:-$default}"
}

store_to_ssm() {
  local json="$1"

  echo "Storing environment config to SSM: ${SSM_PARAM}"
  aws ssm put-parameter \
    --name "$SSM_PARAM" \
    --type "SecureString" \
    --value "$json" \
    --overwrite \
    --query "Version" \
    --output text > /dev/null
  echo "  ✓ Stored (SecureString)"
}

fetch_from_ssm() {
  aws ssm get-parameter \
    --name "$SSM_PARAM" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text 2>/dev/null
}

write_tfvars() {
  local json="$1"
  local stage
  stage=$(echo "$json" | jq -r '.stage')
  local output_file="${ENV_DIR}/${stage}.tfvars"

  mkdir -p "$ENV_DIR"

  {
    echo "# Generated by bootstrap-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Source: SSM ${SSM_PARAM}"
    echo ""
    # Write scalar variables (exclude controllers)
    echo "$json" | jq -r 'to_entries[] | select(.key != "controllers") | "\(.key) = \"\(.value)\""'
    # Write controllers as a list
    local controllers_csv
    controllers_csv=$(echo "$json" | jq -r '.controllers')
    printf 'controllers = [%s]\n' "$(echo "$controllers_csv" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | sed 's/.*/"&"/' | paste -sd ',' -)"
  } > "$output_file"

  echo ""
  echo "Written to: ${output_file}"
}

prompt_all_vars() {
  local existing_json="${1:-}"

  echo "" >&2
  echo "Configure environment variables:" >&2
  echo "" >&2

  local region account_id flux_version test_infra_org test_infra_repo
  local test_infra_branch stage prow_domain kubernetes_org redhat_org controllers publish_account_id

  # Helper to extract existing value from JSON, falling back to provided default
  _default() {
    local key="$1"
    local fallback="$2"
    if [[ -n "$existing_json" ]]; then
      local val
      val=$(echo "$existing_json" | jq -r --arg k "$key" '.[$k] // empty')
      if [[ -n "$val" ]]; then
        echo "$val"
        return
      fi
    fi
    echo "$fallback"
  }

  stage=$(prompt "Deployment stage (prod, staging, dev)" "$(_default stage "${STAGE:-dev}")")

  # Update STAGE from what the user entered
  STAGE="$stage"

  # Set defaults based on stage
  local default_org="ack-prow-staging"
  local default_prow_domain="prow-staging.ack.aws.dev"
  local default_redhat_org="ack-prow-staging"
  local default_kubernetes_org="ack-prow-staging"
  if [[ "$stage" == "prod" ]]; then
    default_org="aws-controllers-k8s"
    default_prow_domain="prow-prod.ack.aws.dev"
    default_redhat_org="redhat-openshift-ecosystem"
    default_kubernetes_org="k8s-operatorhub"
  fi

  region=$(prompt "AWS region" "$(_default region "us-west-2")")
  account_id=$(prompt "AWS account ID" "$(_default account_id "$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo '')")")
  flux_version=$(prompt "Flux chart version" "$(_default flux_version "$(grep 'FLUX_VERSION:' "$BOOTSTRAP_DIR/../flux/flux/version-configmap.yaml" | awk -F'"' '{print $2}')")")
  test_infra_org=$(prompt "GitHub org for test-infra repo" "$(_default test_infra_org "$default_org")")
  test_infra_repo=$(prompt "GitHub repo name for test-infra" "$(_default test_infra_repo "test-infra")")
  test_infra_branch=$(prompt "Git branch for Flux and Prow jobs" "$(_default test_infra_branch "main")")
  prow_domain=$(prompt "Domain for Prow Deck UI" "$(_default prow_domain "$default_prow_domain")")
  kubernetes_org=$(prompt "GitHub org for community-operators fork" "$(_default kubernetes_org "$default_kubernetes_org")")
  redhat_org=$(prompt "GitHub org for community-operators-prod fork" "$(_default redhat_org "$default_redhat_org")")
  controllers=$(prompt "ACK controllers for ECR repos (comma-separated)" "$(_default controllers "ecrpublic")")
  publish_account_id=$(prompt "AWS account ID for ECR Public publishing" "$(_default publish_account_id "${account_id}")")

  # Build JSON
  jq -n \
    --arg region "$region" \
    --arg account_id "$account_id" \
    --arg flux_version "$flux_version" \
    --arg test_infra_org "$test_infra_org" \
    --arg test_infra_repo "$test_infra_repo" \
    --arg test_infra_branch "$test_infra_branch" \
    --arg stage "$stage" \
    --arg prow_domain "$prow_domain" \
    --arg kubernetes_org "$kubernetes_org" \
    --arg redhat_org "$redhat_org" \
    --arg controllers "$controllers" \
    --arg publish_account_id "$publish_account_id" \
    '{
      region: $region,
      account_id: $account_id,
      flux_version: $flux_version,
      test_infra_org: $test_infra_org,
      test_infra_repo: $test_infra_repo,
      test_infra_branch: $test_infra_branch,
      stage: $stage,
      prow_domain: $prow_domain,
      kubernetes_org: $kubernetes_org,
      redhat_org: $redhat_org,
      controllers: $controllers,
      publish_account_id: $publish_account_id
    }'
}

# --- Main ---
echo "=== ACK Test Infra - Environment Bootstrap ==="
echo ""

# Try to fetch existing config from SSM
echo "Checking SSM for existing config: ${SSM_PARAM}"
EXISTING_JSON=$(fetch_from_ssm || true)

if [[ "$FORCE" == "false" && -n "$EXISTING_JSON" ]]; then
  echo "  ✓ Found existing config in SSM"
  STAGE=$(echo "$EXISTING_JSON" | jq -r '.stage')
  write_tfvars "$EXISTING_JSON"
  echo ""
  echo "Usage:"
  echo "  cd bootstrap"
  echo "  terraform init"
  echo "  terraform plan  -var-file=environment/${STAGE}.tfvars"
  echo "  terraform apply -var-file=environment/${STAGE}.tfvars"
  echo ""
  echo "To re-generate, run: $0 --force"
  exit 0
fi

if [[ -n "$EXISTING_JSON" ]]; then
  echo "  ✓ Found existing config in SSM (using as defaults)"
  STAGE=$(echo "$EXISTING_JSON" | jq -r '.stage')
else
  echo "  No existing config found. Will prompt for values."
fi

# Prompt for all values (pass existing JSON so values are used as defaults)
ENV_JSON=$(prompt_all_vars "$EXISTING_JSON")

# Store to SSM
store_to_ssm "$ENV_JSON"

# Write local tfvars
write_tfvars "$ENV_JSON"

echo ""
echo "Usage:"
echo "  cd bootstrap"
echo "  terraform init"
echo "  terraform plan  -var-file=environment/${STAGE}.tfvars"
echo "  terraform apply -var-file=environment/${STAGE}.tfvars"
echo ""
echo "Config is stored in SSM at: ${SSM_PARAM}"
echo "Run this script again to regenerate the local file from SSM."
