# SecretProviderClass for Prow secrets from AWS Secrets Manager
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prow-secrets
  namespace: prow
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "ack/prow/hmac-token"
        objectType: "secretsmanager"
        objectAlias: "hmac-token"
      - objectName: "ack/prow/github-token"
        objectType: "secretsmanager"
        jmesPath:
          - path: "cert"
            objectAlias: "github-cert"
          - path: "appid"
            objectAlias: "github-appid"
      - objectName: "ack/prow/github-pat-token"
        objectType: "secretsmanager"
        objectAlias: "github-pat-token"
  secretObjects:
  - secretName: hmac-token
    type: Opaque
    data:
    - objectName: hmac-token
      key: hmac
  - secretName: github-token
    type: Opaque
    data:
    - objectName: github-cert
      key: cert
    - objectName: github-appid
      key: appid
  - secretName: prowjob-github-pat-token
    type: Opaque
    data:
    - objectName: github-pat-token
      key: token
