ARG GO_VERSION=1.25.4

FROM public.ecr.aws/docker/library/golang:${GO_VERSION}-alpine

WORKDIR /scripts
COPY deploy-docs.sh /scripts/deploy-docs.sh

RUN apk add --no-cache \
    bash \
    git \
    make \
    npm \
    && chmod +x /scripts/deploy-docs.sh

ENTRYPOINT ["/scripts/deploy-docs.sh"]
