FROM debian:bookworm-slim AS base

RUN echo "Installing packages ..." \
    && apt-get update \
    && apt-get install -y --no-install-recommends\
        build-essential \
        ca-certificates \
        make \
        curl \
        git \
        gnupg2 \
        software-properties-common \
        lsb-release \
        wget \
        jq \
        uuid-runtime \
        apt-transport-https \
        unzip \
        gawk

RUN echo "Installing yq ... " \
    && curl -L -s https://github.com/mikefarah/yq/releases/download/v4.31.2/yq_linux_amd64 --output /usr/bin/yq \
    && chmod +x /usr/bin/yq

RUN echo "Installing GitHub cli ..." \
    && curl -fsSL "https://cli.github.com/packages/githubcli-archive-keyring.gpg" | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt-get update \
    && apt-get install -y --no-install-recommends gh
