ARG GO_VERSION=1.22.5

FROM public.ecr.aws/docker/library/golang:${GO_VERSION}-alpine AS builder

RUN apk add --no-cache git

ENV GOPROXY=direct
COPY . .
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ack-build-tools ./prow/jobs/tools/cmd

# Start a new stage from scratch
FROM alpine:latest

COPY --from=builder /go/ack-build-tools /usr/local/bin/
